import Head from "next/head";
import ActiveFriends from "~/components/pages-components/home/ActiveFriends";
import Activities from "~/components/pages-components/home/activities/Activities";
import Hero from "~/components/pages-components/home/Hero";
import Testimonials from "~/components/pages-components/home/Testimonials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hire a friend - help reduce lovlyness</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no"
        />
      </Head>
      <Hero />
      <ActiveFriends />
      <Activities />
      <Testimonials />
    </>
  );
}
